# Generated by Django 6.0.4 on 2026-04-17 10:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_venue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this instance.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date and time this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='The date and time this record was last updated.')),
                ('full_name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('bio', models.TextField(blank=True)),
                ('job_title', models.CharField(blank=True, max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
    ]
