# Generated by Django 6.0.4 on 2026-04-17 11:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this instance.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date and time this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='The date and time this record was last updated.')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('used', 'Used')], default='active', max_length=20)),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='events.registration')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
