# Generated by Django 6.0.4 on 2026-04-19 06:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_waitlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this instance.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date and time this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='The date and time this record was last updated.')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='events.registration')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this instance.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date and time this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='The date and time this record was last updated.')),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], max_length=20)),
                ('provider', models.CharField(default='stripe', max_length=50)),
                ('provider_event_id', models.CharField(blank=True, max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_events', to='events.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
